bookers2-advanced-issue/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get '/serch' => 'searches#search'
end

bookers2-advanced-issue/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  attachment :profile_image, destroy: false

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def follow(user_id)
    active_relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    active_relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
end

bookers2-advanced-issue/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

bookers2-advanced-issue/app/helpers/users_helper.rb
module UsersHelper
end

bookers2-advanced-issue/app/views/users/_book_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, size: "50x50", fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td>
          <span id="favorites-buttons-<%= book.id %>"><%= render 'books/favorite', book: book %></span>
        </td>
        <td><%= link_to "#{book.post_comments.count} コメント", book_path(book.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<h3>投稿数の前日比・前週比</h3>
  <div class="table_width">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>今日の投稿数</th>
          <th>前日の投稿数</th>
          <th>前日比</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @today_book.count %></td>
          <td><%= @yesterday_book.count %></td>
          <td>
            <% if @yesterday_book.count == 0 %>
              前日の投稿が0のため計算できません
            <% else %>
              <% @the_day_before = @today_book.count / @yesterday_book.count.to_f %>
              <%= (@the_day_before * 100).round %>%
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="table_width">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>今週の投稿数</th>
          <th>前週の投稿数</th>
          <th>前週比</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @this_week_book.count %></td>
          <td><%= @last_week_book.count %></td>
          <td>
            <% if @last_week_book.count == 0 %>
              前週の投稿が0のため計算できません
            <% else %>
              <% @the_week_before = @this_week_book.count / @last_week_book.count.to_f %>
              <%= (@the_week_before * 100).round %>%
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div>
    <h4>7日間分の投稿数</h4>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>6日前</th>
          <th>5日前</th>
          <th>4日前</th>
          <th>3日前</th>
          <th>2日前</th>
          <th>1日前</th>
          <th>今日</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @books.created_6day_ago.count %></td>
          <td><%= @books.created_5day_ago.count %></td>
          <td><%= @books.created_4day_ago.count %></td>
          <td><%= @books.created_3day_ago.count %></td>
          <td><%= @books.created_2day_ago.count %></td>
          <td><%= @books.created_yesterday.count %></td>
          <td><%= @books.created_today.count %></td>
        </tr>
      </tbody>
    </table>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js' %>
    <canvas id="myLineChart"></canvas>
    <script>
      $(document).on('turbolinks:load', function() {
        var ctx = document.getElementById("myLineChart");
        var myLineChart = new Chart(ctx, {
          type: 'line',
          data: {
            labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
            datasets: [
              {
                label: '投稿した本の数',
                data: [<%= @books.created_6day_ago.count %>, <%= @books.created_5day_ago.count %>, <%= @books.created_4day_ago.count %>, <%= @books.created_3day_ago.count %>, <%= @books.created_2day_ago.count %>, <%= @books.created_yesterday.count %>, <%= @books.created_today.count %>],
                borderColor: "rgba(0,0,255,1)",
                backgroundColor: "rgba(0,0,0,0)"
              }
            ],
          },
          options: {
            title: {
              display: true,
              text: '7日間の投稿数の比較'
            },
            scales: {
              yAxes: [{
                ticks: {
                  suggestedMax: 10,
                  suggestedMin: 0,
                  stepSize: 1,
                  callback: function(value, index, values){
                    return  value
                  }
                }
              }]
            },
          }
        });
      });
    </script>
  </div>

bookers2-advanced-issue/app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, size: "50x50", fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>
          <% if user != current_user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

bookers2-advanced-issue/app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, size: "100x100", fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user.id) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user.id) %></th>
  </tr>
</table>

<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>

bookers2-advanced-issue/app/views/users/edit.html.erb
user<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

bookers2-advanced-issue/app/views/users/index.html.erb
<div class='container'>
<div class='row'>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='col-md-3'>
    <h2>User info</h2>
    <%= render 'info', user: current_user %>
    <h2 class="mt-3">New book</h2>
    <%= render 'books/form', book: @book %>
  </div>
  <div class='col-md-8 offset-md-1'>
    <h2>Users</h2>
    <%= render 'index',users: @users %>
  </div>
</div>
</div>

bookers2-advanced-issue/app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <div style ="margin-top: 20px;" >
        <%= form_with model:@user, local:true do |f| %>
          <%= f.submit 'フォロー外す', class: 'btn btn-success' %>
        <% end %>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'book_index',books: @books %>
    </div>
  </div>
</div>